version: "3.7"
services:
    # imagem  micro_01 company api
    micro_company:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue_company
        networks:
            - microservices

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # mysql micro 01
    db_micro_01:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3308:3306
        networks:
            - microservices

    #queue company
    queue_company:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microservices


    #redis
    redis:
        image: redis:latest
        networks:
            - microservices


networks:
    microservices:
        driver: bridge
